version: '3.8'

services:
  elasticsearch:
   image: elasticsearch:7.6.2
   container_name: elasticsearch
   environment:
     - discovery.type=single-node
   ports:
    - "9200:9200"


  consul:
    image: consul:1.11.2
    container_name: badger
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - server
      - ui
      - node=server-1
      - bootstrap-expect=1
      - client='0.0.0.0'

  rabbit_queue:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    ports:
      - "5672:5672"
      - "15672:15672"

  search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: searchservice
    ports:
      - "8080:8080"
    depends_on:
      - rabbit_queue
      - consul
      - elasticsearch
